# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/abbaefc5-b276-43ee-a5f8-eb50e46c24a5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/abbaefc5-b276-43ee-a5f8-eb50e46c24a5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/abbaefc5-b276-43ee-a5f8-eb50e46c24a5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@nix" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/76BC-04A2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/abbaefc5-b276-43ee-a5f8-eb50e46c24a5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@swap" "noatime" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
